[2021-08-16 15:47:21,587] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_complex.get_entry_group_result 2021-08-16T15:43:47.414310+00:00 [queued]>
[2021-08-16 15:47:21,746] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_complex.get_entry_group_result 2021-08-16T15:43:47.414310+00:00 [queued]>
[2021-08-16 15:47:21,755] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-08-16 15:47:21,758] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-08-16 15:47:21,762] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-08-16 15:47:21,870] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): get_entry_group_result> on 2021-08-16T15:43:47.414310+00:00
[2021-08-16 15:47:21,939] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_complex', 'get_entry_group_result', '2021-08-16T15:43:47.414310+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_complex.py', '--cfg-path', '/tmp/tmpz5gikufn', '--error-file', '/tmp/tmp629ho10z']
[2021-08-16 15:47:21,950] {standard_task_runner.py:77} INFO - Job 33: Subtask get_entry_group_result
[2021-08-16 15:47:21,911] {standard_task_runner.py:52} INFO - Started process 385 to run task
[2021-08-16 15:47:22,237] {logging_mixin.py:104} INFO - Running <TaskInstance: example_complex.get_entry_group_result 2021-08-16T15:43:47.414310+00:00 [running]> on host 8f195762143d
[2021-08-16 15:47:22,625] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_complex
AIRFLOW_CTX_TASK_ID=get_entry_group_result
AIRFLOW_CTX_EXECUTION_DATE=2021-08-16T15:43:47.414310+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-16T15:43:47.414310+00:00
[2021-08-16 15:47:22,631] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-08-16 15:47:22,640] {bash.py:158} INFO - Running command: echo get_entry_group_result
[2021-08-16 15:47:22,758] {bash.py:169} INFO - Output:
[2021-08-16 15:47:22,762] {bash.py:173} INFO - get_entry_group_result
[2021-08-16 15:47:22,763] {bash.py:177} INFO - Command exited with return code 0
[2021-08-16 15:47:22,842] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=get_entry_group_result, execution_date=20210816T154347, start_date=20210816T154721, end_date=20210816T154722
[2021-08-16 15:47:22,944] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-16 15:47:23,028] {local_task_job.py:146} INFO - Task exited with return code 0
